language: android
jdk: oraclejdk8
sudo: required
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-24
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - sudo ./gradlew clean build